### ISSUE TITLE
Add stability detector to elastic buffer

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#126]
In https://github.com/google-research/bittide/issues/125 I referred to the concept of "elastic buffer stability". This is a bit vague, but we can get a feeling for it by looking at simulation graphs:

![cc](https://user-images.githubusercontent.com/5658854/189741499-f6a5ae05-89d0-4c3b-a28a-a91119e313b3.png)

At some point, clock control will hopefully find itself in a situation where the clocks don't change "that much" anymore - in other words stable. This is a vague definition though, so we should think about what it means to be stable. Alternatively, we can not think of it that much and make it configurable instead.

**Comment by vmchale** [comment]
My naive approach is to track the last 500 signal changes to make sure that it's a net 0 movement over the past 500 requested clock changes.

However, this means taking a `Vec 500 (Unisgned 10)` as state which I suppose is not easy to synthesize, so perhaps we need something more sophisticated. 

(Good news is that since updates are only every 200 clock cycles or so, we can take our time when assessing clock stability?)

**Comment by martijnbastiaan** [comment]
Use a single "target" and make sure the data count stay within `target - 1` and `target + 1`. If it the data count falls below, decrease the target by one. If it exceeds, increase the target by one. 

This way you only need to store two unsigneds: _current target_ and _number of cycles stable_.

**Comment by lmbollen** [comment]
Yeah that's way too large of a vector to synthesize. I really don't think we need something resource intensive for this. I see `SpeedChange` has three possible values, so that only requires two bits of encoding.
I think we should formulate some basic rules that it must meet. A first one could be:
* 90 out of the last 100 speed changes must be `NoChange`.
or 
* the average change in the last 100 speed changes must be less than absolute two `-2 <= average change <=2 `.

The first one can be achieved by storing a `blockRam` with 100 `bool`s that indicate if an incoming `SpeedChange` was not `NoChange` (`NoChange` becomes `False`, `SpeedUp` and `SpeedDown` become `True`). 
Besides that you keep track of a counter that keeps track of the number of True's in the blockRam.
You can then write the`SpeedChange != NoChange` to the blockRam (just increment the address per write).
And you can use that same address to get the `bool` from 100 `SpeedChange`s ago.

Furthermore you can increment the counter when `(incomingChange != NoChange, OldChange == False)` and decrement the counter when `(incomingChange == NoChange, OldChange == True)` For the other cases it evens out. 

If you initialise the blockRam with 100 `True`s and the counter at `100` you should be able to simply set `expectTrue` to `True` when the counter is below 10.

**Comment by lmbollen** [comment]
@martijnbastiaan 's approach requires even less hardware, but each will have its pros and cons.

I think you could do it with even less hardware by just accumulating the `SpeedUp`s and `SpeedDown`s in `Index a` (perhaps `Index 32`) and reducing the offset by 1 every  n ( 1000?) `SpeedChange`s.

**Comment by vmchale** [comment]
@martijnbastiaan yes that makes sense, one moment. 

> I think we should formulate some basic rules that it must meet.

Yes! I did explore that with my naive (too many resources) stability check. In practice, stability (+/-) over the last N cycles seemed to work.

But I will explore Martijn's suggestion first.

**Comment by martijnbastiaan** [comment]
Fixed in #190.
