### ISSUE TITLE
Investigate accidental double-ack in `DoubleBufferedRam`

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#239]
During the integration of VexRisc (https://github.com/bittide/bittide-hardware/pull/198) we found that `DoubleBufferedRam` misbehaves when requesting multiple reads back-to-back. It would behave as follows:

![wavedrom(1)](https://user-images.githubusercontent.com/5658854/214537711-09945f4e-a674-4db4-81fd-0d04c68be9c9.svg)

I.e., it would ACK the request for `a2` while presenting data corresponding to `a1` on the bus. The component should have provided backpressure as follows:

![wavedrom(2)](https://user-images.githubusercontent.com/5658854/214538472-31624b9f-ed73-40fb-83bb-92cf009115b7.svg)

With Contranomy this didn't used to be an issue, as every request would look like:

![wavedrom](https://user-images.githubusercontent.com/5658854/214535532-06f63a5e-2a1a-4fd1-afb9-8bd79b2d53a0.svg)

I.e., Contranomy would simply ignore the wrongly presented data because it wouldn't read back-to-back.

-----

The PR introducing VexRisc piggy-backs a fix for this issue, but IMO this should have been caught by tests. Let's investigate:

 * Why this wasn't caught by tests
 * What we can do to prevent similar issues in the future

**Comment by martijnbastiaan** [comment]
Related: https://github.com/bittide/bittide-hardware/pull/198#discussion_r1082542395

**Comment by cuddlefishie** [comment]
By the wishbone specification technically outputting two requests in the "same" CYC+STB phase is allowed, and a slave is also allowed to keep asserting ACK. The specification uses this "multiple requests in a row" as an example to introduce registered feedback, so it seems *discouraged* but legal.

The `driveStandard` function in `clash-protocols` always deasserts CYC after a transaction, so any test using this would not have caught this error.

I also noticed that the `validateLenient` circuit sometimes steps "too quickly" when updating the validation state. I will fix this.

I will also add an option to the `driveStandard` function so that the number of cycles where CYC+STB are deasserted can be configured, that would allow it to also test situations where they are never deasserted.

**Comment by cuddlefishie** [comment]
Changes to clash-protocols are implemented in https://github.com/clash-lang/clash-protocols/pull/52 and the changed/added tests for bittide are implemented in #251
