### ISSUE TITLE
Update to newer GHC

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#455]
Depends on:

- [X] ~~https://github.com/bittide/bittide-hardware/pull/468~~ https://github.com/bittide/bittide-hardware/pull/500
- [x] Upgrade `clash-protocols` (~~@cuddlefishie~~ @martijnbastiaan)
  - [x] https://github.com/clash-lang/clash-protocols/pull/63
- [x] Update `clash-vexriscv` (@cuddlefishie @martijnbastiaan)
  - [x] https://github.com/clash-lang/clash-vexriscv/pull/15
  - [X] ~~Add 9.6 support?~~
- [x] Upgrade `circuit-notation` (~~@martijnbastiaan~~ @kleinreact)
  - [x] https://github.com/cchalmers/circuit-notation/pull/18
  - [x] https://github.com/cchalmers/circuit-notation/pull/19
  - [x] https://github.com/cchalmers/circuit-notation/pull/21

**Comment by kleinreact** [comment]
As it turns out, there are some bigger obstacles on the way of our idea to turn circuits into constrained arrows and to use [proc notation](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/arrows.html) instead of the `circuit-notation` plugin as well. Unfortunately, the `Arrows` language extension still is buggy in terms of supporting constrained arrows properly: https://gitlab.haskell.org/ghc/ghc/-/issues/7828

---

To give some more background: we cannot turn circuits into Arrows in general, as this would mean that any function can be lifted into a circuit, which is incompatible with the `Fwd` and `Bwd` separation used by `circuit-notation` and `clash-protocols` at the type level. A way out of this dilemma are constrained arrows, as for example supported with the [Constrained Categories](https://github.com/leftaroundabout/constrained-categories) package, which enable the use of more specific categories than just `(->)`. In this scope a well-defined notion of `circuits-as-arrows` can be defined.

However, the `Arrows` language extension seems not to be well prepared for those kinds of applications as well. While it can be utilized with the [`RebindableSyntax`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/rebindable_syntax.html#extension-RebindableSyntax) extension to inject custom arrow primitives, it breaks as soon as the new arrow primitives are equipped with constraints (see the issue mentioned above). Other than that, it also utilizes some unnecessary assumptions of being in `(->)`. For example, it turns `proc`-code into arrow applications of `arr (\x -> x)` instead of using the identity arrow directly. This way required constraints on the usage of some constrained arrow primitives cannot be supported properly. 

---

As a consequence, there seems to be no good alternative right now than upgrading `circuit-notations` with each new version of GHC to keep at least to status quo.

**Comment by martijnbastiaan** [comment]
We've been making quite some progress, but `clash-vexriscv` turns out to be very brittle. So I'll have to sit down with @cuddlefishie to see what we can do at some point.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/bittide/bittide-hardware/pull/500
