### ISSUE TITLE
Add `fourmolu` as a formatter

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#548]
See discussion at https://github.com/clash-lang/clash-protocols/pull/79. Ideally this would be easy to integrate into git hooks for people that want that. Like for `clash-protocols`: let's follow fourmolu's opinions as much as possible. The point is to be consistent, not to impose _yet another_ style to get used to.

**Comment by rowanG077** [comment]
The `format.sh` script in `diff ` mode is basically designed to be be used as the git pre-commit. I did play around with it a little bit on the protocols PR but in the end did not introduce it because commit a pre-commit hook requires everyone to configure it manually. Personally I configure my editor to run the formatter on save.
